### ISSUE TITLE
No ranks for regular

### ISSUE THREAD

**Issue by hexandwhy** [sparkychild/FoxieBot#4]
Things like
+
%
@
works but there doesn't seem to be a sign for regulars.

**Comment by sparkychild** [comment]
can you be more specific on what youre aiming at?

**Comment by sparkychild** [comment]
By default, a space signifies reg user in PS.

**Comment by hexandwhy** [comment]
For example, the bot auth system. I can't seem to get somebody promoted/demoted to bot Regular, and I seem to have to manually erase the person from the list.

**Comment by sparkychild** [comment]
use '.auth user, deauth' to so that

**Comment by sparkychild** [comment]
do*

**Comment by hexandwhy** [comment]
Okay, thanks.
